---

- hosts: 172.31.6.200 #all #172.31.234.60
  tasks:
# -----------------------------------------------


    # -----------------------------------------------
    # si boro kernel viejo necesita reinicia
    - name: Reboot
      shell: reboot
      async: 1
      poll: 0

    - name: Esperar que arranque el host
      wait_for_connection:
        connect_timeout: 40
        sleep: 5
        delay: 5
        timeout: 300

    - name: pp
      shell: |
        rmmod pata_acpi;
        leapp answer --section remove_pam_pkcs11_module_check.confirm=True;
