---
- hosts: all
  #become_user: root 
  #remote_user: host
  
  tasks:
    # ----------------------------------------
    # Verifie post upgrade
    - name: pp1
      shell: |
        # Verify that the current OS version is Red Hat Enterprise Linux 8
        cat /etc/redhat-release | grep {{ target_os_version}}
        # Check the OS kernel version:
        uname -r| grep {{ target_os_version}} 
        #Verify that the correct product is installed
        subscription-manager list --installed | grep Version || grep {{ target_os_version}}
        #Verify that the release version is set to the target OS version immediately after the upgrade:
        subscription-manager release || grep {{ target_os_version}}

        # Securiry Policy
        ausearch -m AVC,USER_AVC -ts boot
        cat <<EOF 
        SELINUX=enforcing
        SELINUXTYPE=targeted 
        EOF > /etc/selinux/config
      register: stdout
  
    # ----------------------------------------
    - name: Reboot
      shell: reboot
      async: 1
      poll: 0

    - name: Esperar que arranque el host
      wait_for_connection:
        connect_timeout: 40
        sleep: 5
        delay: 5
        timeout: 300
