---

- block:
  - name: Install packages
    ansible.builtin.yum:
      name:
        - katello-agent
        - leapp-upgrade
        - leapp-repository
        - leapp-upgrade-el7toel8
        - cockpit-leapp.noarch
      state: latest

  - name: Copy leapp file
    ansible.builtin.copy:
      src: "leapp-data18.tar.gz"
      dest: "/tmp"

  - name: Descompress leapp file
    shell: tar -zxvf "/tmp/leapp-data18.tar.gz -C /etc/leapp/files"

