---

- block:
  - name: Install packages
    ansible.builtin.yum:
      name:
        - katello-agent
        - leapp-upgrade
        - leapp-repository
        - leapp-upgrade-el7toel8
        - cockpit-leapp.noarch
      state: latest

  - name: Copy leapp file
    ansible.builtin.copy:
      src: "{{ download_url}}"
      dest: "{{ download_folder}}"

  - name: Descompress leapp file
    shell: cd "{{ download_folder}}"; tar -zxvf "{{download_url}}"

